= Additional beans for Spring Boot 3.4+

This project provide Spring Boot Starters for configuring additional beans without backing off Spring Boot auto-configured one.
Thanks to https://github.com/spring-projects/spring-boot/commit/2ecb4ebd4947cfe3abd28d9a611186b680a59959.

== Getting started

=== Additional redis beans

Add dependency:
[source,kotlin]
----
implementation("io.additionalbeans:additional-beans-redis-spring-boot-starter")
----

Then you can configure it as following:
[source,yaml]
----
# primary redis service
spring.data.redis:
  host: 127.0.0.1
  port: 6379
  client-name: default

additional.redis.prefixes: [foo, bar]
# additional foo redis service, inherit from primary properties
foo.data.redis:
  host: 127.0.0.1 # not required because it's equal to spring.data.redis.host
  database: 1
  client-name: foo
bar.data.redis:
  database: 2
  client-type: jedis
----

And you can inject beans using `@Qualifier` as following:
[source,java]
----

	@Autowired
	@Qualifier("fooRedisConnectionFactory")
	private RedisConnectionFactory fooRedisConnectionFactory;

	@Autowired
	@Qualifier("barRedisConnectionFactory")
	private RedisConnectionFactory barRedisConnectionFactory;

	@Autowired
	@Qualifier("fooRedisTemplate")
	private RedisTemplate<Object, Object> fooRedisTemplate;

	@Autowired
	@Qualifier("barRedisTemplate")
	private RedisTemplate<Object, Object> barRedisTemplate;

	@Autowired
	@Qualifier("fooStringRedisTemplate")
	private StringRedisTemplate fooStringRedisTemplate;

	@Autowired
	@Qualifier("barStringRedisTemplate")
	private StringRedisTemplate barStringRedisTemplate;
----

=== Additional jdbc beans

Add dependency:
[source,kotlin]
----
implementation("io.additionalbeans:additional-beans-jdbc-spring-boot-starter")
----

Then you can configure it as following:
[source,yaml]
----
# primary data source
spring.datasource:
  driver-class-name: org.h2.Driver
  url: jdbc:h2:mem:spring
  hikari.minimum-idle: 10
  hikari.maximum-pool-size: 100


additional.jdbc.prefixes: [foo, bar]
# additional data sources, inherit from primary properties
foo.datasource:
  driver-class-name: org.h2.Driver # not required because it's equal to spring.data.redis.host
  url: jdbc:h2:mem:foo
  hikari.maximum-pool-size: 40
bar.datasource:
  url: jdbc:h2:mem:bar
  hikari.maximum-pool-size: 50
----

And you can inject beans using `@Qualifier` as following:
[source,java]
----
	@Autowired
	@Qualifier("fooDataSource")
	private DataSource fooDataSource;

	@Autowired
	@Qualifier("barDataSource")
	private DataSource barDataSource;

	@Autowired
	@Qualifier("fooTransactionManager")
	private DataSourceTransactionManager fooTransactionManager;

	@Autowired
	@Qualifier("barTransactionManager")
	private DataSourceTransactionManager barTransactionManager;

	@Autowired
	@Qualifier("fooJdbcTemplate")
	private JdbcTemplate fooJdbcTemplate;

	@Autowired
	@Qualifier("barJdbcTemplate")
	private JdbcTemplate barJdbcTemplate;

	@Autowired
	@Qualifier("fooNamedParameterJdbcTemplate")
	private NamedParameterJdbcTemplate fooNamedParameterJdbcTemplate;

	@Autowired
	@Qualifier("barNamedParameterJdbcTemplate")
	private NamedParameterJdbcTemplate barNamedParameterJdbcTemplate;

	@Autowired
	@Qualifier("fooJdbcClient")
	private JdbcClient fooJdbcClient;

	@Autowired
	@Qualifier("barJdbcClient")
	private JdbcClient barJdbcClient;
----

=== Additional kafka beans

Add dependency:
[source,kotlin]
----
implementation("io.additionalbeans:additional-beans-kafka-spring-boot-starter")
----

Then you can configure it as following:
[source,yaml]
----
# primary redis service
spring.kafka:
  bootstrap-servers: localhost:9092
  client-id: default

additional.redis.prefixes: [foo, bar]
foo.data.redis:
  client-id: foo
bar.data.redis:
  client-id: bar
----

And you can inject beans using `@Qualifier` as following:
[source,java]
----

	@Autowired
	@Qualifier("fooKafkaProducerFactory")
	private DefaultKafkaProducerFactory<?, ?> fooKafkaProducerFactory;

	@Autowired
	@Qualifier("barKafkaProducerFactory")
	private DefaultKafkaProducerFactory<?, ?> barKafkaProducerFactory;

	@Autowired
	@Qualifier("fooKafkaConsumerFactory")
	private DefaultKafkaConsumerFactory<?, ?> fooKafkaConsumerFactory;

	@Autowired
	@Qualifier("barKafkaConsumerFactory")
	private DefaultKafkaConsumerFactory<?, ?> barKafkaConsumerFactory;

	@Autowired
	@Qualifier("fooKafkaTemplate")
	private KafkaTemplate<?, ?> fooKafkaTemplate;

	@Autowired
	@Qualifier("barKafkaTemplate")
	private KafkaTemplate<?, ?> barKafkaTemplate;

	@Autowired
	@Qualifier("fooKafkaAdmin")
	private KafkaAdmin fooKafkaAdmin;

	@Autowired
	@Qualifier("barKafkaAdmin")
	private KafkaAdmin barKafkaAdmin;
----

=== Additional MongoDB beans

Add dependency:
[source,kotlin]
----
implementation("io.additionalbeans:additional-beans-mongodb-spring-boot-starter")
----

Then you can configure it as following:
[source,yaml]
----
# primary redis service
spring.data.mongodb:
  host: 127.0.0.1
  port: 27017

additional.mongodb.prefixes: [foo, bar]
foo.data.mongodb:
  port: 27018
  database: foo
bar.data.mongodb:
  port: 27019
  database: bar
----

And you can inject beans using `@Qualifier` as following:
[source,java]
----
	@Autowired
	@Qualifier("fooMongoClient")
	private MongoClient fooMongoClient;

	@Autowired
	@Qualifier("barMongoClient")
	private MongoClient barMongoClient;

	@Autowired
	@Qualifier("fooMongoDatabaseFactory")
	private MongoDatabaseFactory fooMongoDatabaseFactory;

	@Autowired
	@Qualifier("barMongoDatabaseFactory")
	private MongoDatabaseFactory barMongoDatabaseFactory;

	@Autowired
	@Qualifier("fooMongoTemplate")
	private MongoTemplate fooMongoTemplate;

	@Autowired
	@Qualifier("barMongoTemplate")
	private MongoTemplate barMongoTemplate;
----

=== Additional RabbitMQ beans

Add dependency:
[source,kotlin]
----
implementation("io.additionalbeans:additional-beans-rabbitmq-spring-boot-starter")
----

Then you can configure it as following:
[source,yaml]
----
# primary redis service
spring.rabbitmq:
  host: 127.0.0.1
  port: 5672

additional.mongodb.prefixes: [foo, bar]
foo.rabbitmq:
  port: 5673
  username: foo
bar.rabbitmq:
  port: 5674
  username: bar
----

And you can inject beans using `@Qualifier` as following:
[source,java]
----
	@Autowired
	@Qualifier("fooConnectionFactory")
	private ConnectionFactory fooConnectionFactory;

	@Autowired
	@Qualifier("barConnectionFactory")
	private ConnectionFactory barConnectionFactory;

	@Autowired
	@Qualifier("fooRabbitTemplate")
	private RabbitTemplate fooRabbitTemplate;

	@Autowired
	@Qualifier("barRabbitTemplate")
	private RabbitTemplate barRabbitTemplate;

	@Autowired
	@Qualifier("fooAmqpAdmin")
	private AmqpAdmin fooAmqpAdmin;

	@Autowired
	@Qualifier("barAmqpAdmin")
	private AmqpAdmin barAmqpAdmin;
----